# netlify.toml — BZB Music

[build]
  # For a plain HTML/CSS site at the repo root:
  publish = "."

# ---- Caching ----
# Cache images aggressively; they rarely change.
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML so updates show immediately.
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/terms.html"
  [headers.values]
    Cache-Control = "no-store"

# ---- Security headers (safe defaults) ----
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # Keep 'unsafe-inline' for styles only if you use inline CSS anywhere:
    Content-Security-Policy = "default-src 'self'; img-src 'self' https: data:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; frame-ancestors 'none'"

# ---- Redirects (optional) ----
# Netlify will handle apex→www once you set 'www' as Primary in the UI.
# If you still want an explicit rule, you can add one like this:
# [[redirects]]
#   from = "https://bzbmusic.com/*"
#   to = "https://www.bzbmusic.com/:splat"
#   status = 301
#   force = true
